ci:
  skip: [ty]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.31.6
    hooks:
      - id: basedpyright
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check
        language: python
