site_name: Kabukit
site_url: https://daizutabi.github.io/kabukit/
site_description: 日本の株式投資分析を、もっと手軽に、もっと速く。J-QuantsとEDINETのデータを、コマンドラインやPythonコードから快適に扱うためのモダンなツールキットです。
site_author: daizutabi
repo_url: https://github.com/daizutabi/kabukit/
repo_name: daizutabi/kabukit
edit_uri: edit/main/docs/
theme:
  logo: assets/images/logo.svg
  name: material
  font:
    text: Fira Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
plugins:
  - search
  - markdown-exec
  - mkapi:
      debug: true
  - mkdocs-nbsync:
      src_dir: ../notebooks
  # - marimo:
  #     enabled: true
  #     display_code: true
markdown_extensions:
  - admonition
  - attr_list
  - cjk_autojoin
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - はじめに: index.md
  - 利用ガイド:
      - CLI: guides/cli.md
      - J-Quants API: guides/jquants.md
      - EDINET API: guides/edinet.md
      - キャッシュの活用: guides/cache.md
  # - "コンセプト":
  #     - "概要": "concept/index.md"
  #     - "コア指標": "concept/core_indicators.md"
  # - "ワークフロー":
  #     - "全体像": "workflow/index.md"
  #     - "フェーズ1: 市場概観": "workflow/01_market_overview.md"
  #     - "フェーズ2: モデル構築": "workflow/02_model_building.md"
  #     - "フェーズ3: スクリーニング": "workflow/03_screening.md"
  #     - "フェーズ4: 定性的深掘り": "workflow/04_deep_dive.md"
  # - "データ層":
  #     - "概要": "data_layer/index.md"
  #     - "指標計算ポリシー": "data_layer/indicator_calculation.md"
  #     - "調整済み株式数": "data_layer/adjusted_shares.md"
  #     - "J-Quants スキーマ": "data_layer/jquants_schema.md"
  #     - "実践的な注意点": "data_layer/practical_notes.md"
  - API リファレンス: $api/kabukit.***
extra_css:
  - assets/css/kabukit.css
